### ISSUE TITLE
DataFilter::read_file is broken on ARM32 (Raspberry Pi)

### ISSUE THREAD

**Issue by GrahamBriggs** [brainflow-dev/brainflow#135]
Build brainflow libs from latest source code on Raspberry Pi.

Try to run the C++ serialization sample program.

The execution enters DataFilter::read_file and never returns.

![Screen Shot 2020-11-14 at 6 02 54 PM](https://user-images.githubusercontent.com/5171343/99161133-b4379b80-26a3-11eb-835a-dacaae95eb61.png)

**Comment by Andrey1994** [comment]
I can reproduce it, no idea why but I will try to add breakpoints inside read_file method and check

**Comment by Andrey1994** [comment]
I think I've solved original issue but now I am getting memory error which I dont understand...
The issue is in EOF, need to change `c != EOF` by `!feof(fp)` here https://github.com/brainflow-dev/brainflow/blob/master/src/data_handler/data_handler.cpp#L794 and here https://github.com/brainflow-dev/brainflow/blob/master/src/data_handler/data_handler.cpp#L852
