### ISSUE TITLE
the method "bluetooth_write_data" in the file "bt_lib_board.cpp", has a status code error.

### ISSUE THREAD

**Issue by cz4447** [brainflow-dev/brainflow#544]
**Describe the bug**
the dynamic library method "bluetooth_write_data" return the length of the data had been wrote, but in the file "bt_lib_board.cpp" line 182, the method "bluetooth_write_data" check the length as a status code. When the return length
equal 1, the same with "SocketBluetoothReturnCodes::WSA_STARTUP_ERROR", it will raise an error.

**Comment by Andrey1994** [comment]
methods send and recv(bluetooth_write_data and bluetooth_read_data) return number of bytes written instead error code, in case of errors they return -1. its quite common. Also you probably using old version since it was changed in this commit https://github.com/brainflow-dev/brainflow/commit/87b28b0caafc06561b27b5c9fc07210a425a8a7a#diff-a4a981c61df100e6b31eb5c05d20e4aa7513da62bdecd554c89c383236cf010b
