### ISSUE TITLE
Publish brainflow on bioconductior

### ISSUE THREAD

**Issue by Pandapip1** [brainflow-dev/brainflow#713]
**Use case:**

Publishing the brainflow R package on [bioconductor](https://bioconductor.org/) will make it much more accessible to install.

**Describe the solution you'd like:**

Brainflow should be published on bioconductor.

**Describe alternatives you've considered:**

If you could get brainflow on CRAN, that would be even better, but that would be a bit of a stretch.

**Comment by Andrey1994** [comment]
Hi!

I thought about CRAN but it will still require some manual setup because brainflow R package uses reticulate and calls python code. So proper python setup is required and as far as I know cannot be easily managed by CRAN. So unfortunatelly its not an option.

I will read about bioconductor, have not heard about it before

**Comment by Andrey1994** [comment]
seems like the same is the case for bioconductor and for R package in general, so no plans to fix

**Comment by Pandapip1** [comment]
Mind updating this issue to be closed as 'not planned' instead of 'completed?'
